export const GET_SCENIC_SPOT = "GET_SCENIC_SPOT";
export const GET_SCENIC_SPOT_SUCCESS = "GET_SCENIC_SPOT_SUCCESS";
export const GET_SCENIC_SPOT_ERROR = "GET_SCENIC_SPOT_ERROR";

export const GET_RESTAURANT = "GET_RESTAURANT";
export const GET_RESTAURANT_SUCCESS = "GET_RESTAURANT_SUCCESS";
export const GET_RESTAURANT_ERROR = "GET_RESTAURANT_ERROR";

export const GET_HOTEL = "GET_HOTEL";
export const GET_HOTEL_SUCCESS = "GET_HOTEL_SUCCESS";
export const GET_HOTEL_ERROR = "GET_HOTEL_ERROR";

export const GET_ACTIVITY = "GET_ACTIVITY";
export const GET_ACTIVITY_SUCCESS = "GET_ACTIVITY_SUCCESS";
export const GET_ACTIVITY_ERROR = "GET_ACTIVITY_ERROR";
